name: eck/elk installer on k8s
on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ./config
          export KUBECONFIG=$(pwd)/config
          echo $KUBECONFIG
          
          echo "1- ADD HELM REPO AND UPDATE"
          helm repo add elastic https://helm.elastic.co
          helm repo update

          echo "2- GLOBAL INSTALL"
          helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace

          echo "3- DEPLOY ELASTICSEARCH MANIFIEST"
          cat <<EOF | kubectl apply -f -
          apiVersion: elasticsearch.k8s.elastic.co/v1
          kind: Elasticsearch
          metadata:
            name: quickstart
          spec:
            version: 8.17.4
            nodeSets:
            - name: default
              count: 3
              config:
                node.store.allow_mmap: false
              podTemplate:
                spec:
                  containers:
                  - name: elasticsearch
                    resources:
                      requests:
                        memory: 8Gi
                        cpu: 4
                      limits:
                        memory: 16Gi
                        cpu: 6
              volumeClaimTemplates:
              - metadata:
                  name: elasticsearch-data
                spec:
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 100Gi
          EOF

          echo "4- WAIT 61 SECONDS AND CHECK"
          sleep 61
          kubectl get pods --selector='elasticsearch.k8s.elastic.co/cluster-name=quickstart'

          echo "5- GET PASSWORD"
          PASSWORD=$(kubectl get secret quickstart-es-elastic-user -o go-template='{{.data.elastic | base64decode}}')
          echo $PASSWORD

          echo "6- DEPLOY KIBANA"
          cat <<EOF | kubectl apply -f -
          apiVersion: kibana.k8s.elastic.co/v1
          kind: Kibana
          metadata:
            name: quickstart
          spec:
            version: 8.17.4
            count: 1
            elasticsearchRef:
              name: quickstart
            podTemplate:
              spec:
                containers:
                - name: kibana
                  resources:
                    requests:
                      memory: 4Gi
                      cpu: 2
                    limits:
                      memory: 8Gi
                      cpu: 4
          EOF

          echo "7- WAIT 61 SECONDS AND CHECK"
          sleep 61
          kubectl get pod --selector='kibana.k8s.elastic.co/name=quickstart'

          echo "8- EXPOSE LB-KIBANA LOADBALANCER"
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: lb-kibana
          spec:
            selector:
              common.k8s.elastic.co/type: kibana
              kibana.k8s.elastic.co/name: quickstart
            ports:
            - protocol: TCP
              port: 5601
              targetPort: 5601
            type: LoadBalancer
          EOF

          echo "9- WAIT 183 SECONDS AND CHECK"
          sleep 183
          kubectl get svc | grep lb-kibana
